version: '3.9'

services:
  db:
    image: db
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=test_user
      - POSTGRES_DB=test_db